import {EXAMPLES_BY_TYPE,INPUT_TYPES,parseNames,runBatch,consolidate,summarize} from './engine.js';
import {METHOD_ROWS,exportWorkbook} from './export.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let running=false,controller=null,results=[],settings={},selected=null,renderTimer=null;
function updateInput(){const drugs=parseNames($('#names').value),count=drugs.length;$('#input-count').textContent=`${count} drug${count===1?'':'s'}`;$('#run').disabled=running||!count;const dirty=results.length>0&&!running&&(JSON.stringify(drugs.map(d=>d.input))!==JSON.stringify(results.map(d=>d.input))||settings.inputType!==$('#input-type').value);$('#stale-notice').hidden=!dirty;$('#export').disabled=running||!results.length||dirty;}
function updateType(){const type=$('#input-type').value;$('#input-type-hint').textContent='Enter generic drug names, active ingredient names, brand names, or a mix.';$('#names').placeholder=EXAMPLES_BY_TYPE[type].join('\n');$('#example-hint').textContent='Examples: '+EXAMPLES_BY_TYPE[type].join(', ')+'.';updateInput();}
$('#names').addEventListener('input',updateInput);$('#input-type').addEventListener('change',updateType);
$('#load-examples').addEventListener('click',()=>{if(running)return;$('#names').value=EXAMPLES_BY_TYPE[$('#input-type').value].join('\n');updateInput();$('#status').textContent='Three examples loaded. Edit these names or enter your own drug list.';});
function setRunning(value){running=value;for(const el of document.querySelectorAll('#names,#input-type,#load-examples'))el.disabled=value;$('#stop').hidden=!value;$('#progress').hidden=!value;updateInput();}
function tag(state){return `<span class="tag ${/Partial|Stopped|Not processed/.test(state)?'error':/Zero/.test(state)?'zero':''}">${esc(state)}</span>`;}
function render(){const all=consolidate(results);$('#m-drugs').textContent=results.filter(r=>r.finished).length;$('#m-ndcs').textContent=all.length.toLocaleString();$('#empty').hidden=results.length>0;$('#results-table').hidden=!results.length;$('#results-table').innerHTML=`<p class="hint">Export the <strong>NDC mapping</strong> sheet for your drug-to-NDC list. Select a drug to see the returned names and codes.</p><div class="table-scroll"><table><thead><tr><th>Drug name</th><th>FDA products</th><th>Package NDCs</th><th>Status</th></tr></thead><tbody>${results.map((r,i)=>{const s=summarize(r);return `<tr><td><button data-detail="${i}">${esc(r.input)}</button><small>${esc(s.inputType)}</small></td><td>${s.products}</td><td><strong>${s.ndc}</strong></td><td>${tag(s.state)}</td></tr>`;}).join('')}</tbody></table></div>`;if(selected!==null)showDetail(selected);}
$('#results-table').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b){selected=Number(b.dataset.detail);showDetail(selected);}});
function showDetail(i){const r=results[i];if(!r)return;const s=summarize(r),rows=consolidate([r]);$('#detail').hidden=false;$('#detail').innerHTML=`<h3>${esc(r.input)}</h3><p><strong>FDA updated:</strong> ${esc(r.fdaUpdated||'Unavailable')}</p>${s.notes?`<div class="notice">${esc(s.notes)}</div>`:''}<p>${rows.length} package NDCs. Showing ${Math.min(50,rows.length)}; the workbook includes every code.</p><div class="table-scroll"><table><thead><tr><th>FDA package NDC</th><th>NDC11</th><th>Generic name</th><th>Brand name</th></tr></thead><tbody>${rows.slice(0,50).map(x=>`<tr><td class="mono">${esc(x.raw.join(' | '))}</td><td class="mono">${esc(x.ndc)}</td><td>${esc(x.products.join(' | '))}</td><td>${esc(x.brands.join(' | '))}</td></tr>`).join('')}</tbody></table></div>`;}
async function start(){if(running)throw new Error('A batch is already running.');const drugs=parseNames($('#names').value);if(!drugs.length)throw new Error('Enter at least one drug name.');if(drugs.length>200)throw new Error('Use up to 200 unique drugs per batch.');if(drugs.some(d=>d.input.length>200))throw new Error('Use up to 200 characters per drug name.');settings={inputType:$('#input-type').value,website:location.origin+location.pathname};controller=new AbortController();selected=null;results=[];$('#detail').hidden=true;render();setRunning(true);$('#progress').max=drugs.length;$('#progress').value=0;$('#status').textContent='Connecting to openFDA…';try{results=await runBatch(drugs,{...settings,signal:controller.signal},(data,done,message)=>{results=data;$('#status').textContent=message;$('#progress').value=done;if(!renderTimer)renderTimer=setTimeout(()=>{renderTimer=null;render();},300);});clearTimeout(renderTimer);renderTimer=null;render();$('#status').textContent=results.some(r=>r.errors.length||!r.finished)?'Some lookups did not finish. You can export the partial results or retry the batch.':`Batch complete: ${results.length} drug${results.length===1?'':'s'}. Your NDC export is ready.`;}finally{setRunning(false);}return results.map(summarize);}
$('#run').addEventListener('click',()=>start().catch(e=>{$('#status').textContent=e.message;setRunning(false);}));$('#stop').addEventListener('click',()=>{controller?.abort();$('#status').textContent='Stopping and preserving completed evidence…';});
$('#export').addEventListener('click',()=>{try{exportWorkbook(results,settings);$('#status').textContent='Excel export prepared. Check your browser downloads for the workbook.';}catch(e){$('#status').textContent='Export failed: '+e.message;}});
$('#method-details').innerHTML=METHOD_ROWS.map(([k,v])=>`<p><strong>${esc(k)}.</strong> ${v.startsWith('https://')?`<a href="${esc(v)}" target="_blank" rel="noopener noreferrer">Official documentation ↗</a>`:esc(v)}</p>`).join('');updateType();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{document.modelContext.registerTool({name:'map_drug_names',title:'Map drug names to NDCs',description:'Query the public openFDA NDC Directory using the page workflow. Replaces current page results.',inputSchema:{type:'object',properties:{input_type:{type:'string',enum:['ingredient','generic','brand','mixed']},names:{type:'array',items:{type:'string'},minItems:1,maxItems:200}},required:['names'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!Array.isArray(input.names)||input.names.some(x=>typeof x!=='string'||x.length>1000)||input.names.length>200)throw new Error('Provide up to 200 drug names.');if(running)throw new Error('A batch is running.');if(input.input_type&&!Object.hasOwn(INPUT_TYPES,input.input_type))throw new Error('Unsupported input type.');$('#input-type').value=input.input_type||'mixed';updateType();$('#names').value=input.names.join('\n');updateInput();return {content:[{type:'text',text:JSON.stringify(await start())}]};}},{signal:lifecycle.signal});document.modelContext.registerTool({name:'get_ndc_batch_summary',title:'Read NDC batch results',description:'Read batch status and drug summaries.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async()=>({content:[{type:'text',text:JSON.stringify({running,uniqueNdc:consolidate(results).length,drugs:results.map(summarize)})}]})},{signal:lifecycle.signal});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch(e){console.info('Optional browser tools unavailable:',e.message);}}
