import {consolidate,summarize,INPUT_TYPES} from './engine.js';
export const METHOD_ROWS=[
['Purpose','Enter drug names, retrieve package NDCs from the current openFDA NDC Directory, and export the results.'],
['Workflow','Enter names → search openFDA → collect package NDCs from every returned product → format and deduplicate → export Excel.'],
['Search modes','Any drug name searches active_ingredients.name, generic_name and brand_name. The ingredient, generic and brand options search only the selected field. Enter one drug name per line. Multiword names may use spaces or underscores. Underscores are converted to spaces before each line is searched as one quoted phrase using the FDA search syntax.'],
['Result selection','Include every product returned by the API query. No extra exact-name filter, salt-form classifier, missing-ingredient exclusion or manual approval step is applied. API search results can include salt forms, combinations and brand variants.'],
['Scope','The API query restricts results to finished HUMAN PRESCRIPTION DRUG and HUMAN OTC DRUG records in the current directory. There is no historical reconstruction or study-year filter.'],
['NDC mapping sheet','One row per input drug and distinct package NDC. FDA package NDCs are source values. NDC11 is derived by format conversion only. The same NDC can appear for different input drugs.'],
['Formatting','Convert segmented 4-4-2, 5-3-2 and 5-4-1 codes to 11-digit 5-4-2. Retain original codes and leading zeros as text. Unsupported or ambiguous codes remain in the main export with a blank NDC11; no code is guessed.'],
['Drug summary sheet','Counts of distinct FDA product records and package NDCs per input, plus query status and explanations for zero results or incomplete requests. Counts are calculated from API results.'],
['API records sheet','Original product and package fields with source URLs. Products without package records are retained with blank package fields. Missing source fields remain blank.'],
['Pagination and failures','Fetch all result pages, 1000 records per request, up to the FDA skip limit of 25000. Failed, interrupted or limited requests are marked Partial or Stopped and exports are marked PARTIAL. Errors are never reported as confirmed zero results.'],
['Coverage','Returned NDCs represent the selected FDA search, not an independently validated clinical drug definition. Current-directory results do not establish historical completeness or FDA approval.'],
['Privacy','Queries go directly from your browser to openFDA. Results and the exported workbook are generated in your browser.'],
['FDA fields','https://open.fda.gov/apis/drug/ndc/searchable-fields/'],
['FDA query syntax','https://open.fda.gov/apis/query-parameters/'],
['FDA directory coverage','https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory']];
export function buildSheets(results,settings={}){
 const sheets=[],add=(name,headers,rows)=>sheets.push({name,rows:[headers,...rows]});
 add('NDC mapping',['Input drug','FDA package NDC','NDC11','Generic name','Brand name'],results.flatMap(r=>consolidate([r]).map(x=>[r.input,x.raw.join(' | '),x.ndc,x.products.join(' | '),x.brands.join(' | ')])));
 add('Drug summary',['Input drug','Input type','FDA products','Package NDCs','Status','Notes / errors','FDA data updated','Lookup started UTC','Lookup finished UTC'],results.map(r=>{const s=summarize(r);return [s.input,s.inputType,s.products,s.ndc,s.state,s.notes,r.fdaUpdated,r.started,r.finished];}));
 const records=results.flatMap(r=>[...r.fda,...r.fdaProducts.filter(p=>!p.packages)]);
 add('API records',['Input drug','FDA package NDC','NDC11','Product NDC','Generic name','Brand name','Active ingredients and strengths','Labeler','Dosage form','Routes','Package description','Marketing start date','Marketing end date','Sample','Search source URL','Product source URL'],records.map(x=>[x.input,x.raw,x.ndc,x.productNdc,x.product,x.brand,x.ingredients,x.labeler,x.dosageForm,x.route,x.description,x.first,x.last,x.sample,x.source,x.productSource]));
 add('Methods and workflow',['Topic','Description'],[['Batch status',results.some(r=>!r.finished||r.errors.length)?'PARTIAL — some lookups did not finish':'Completed'],['Exported UTC',new Date().toISOString()],['Website',settings.website||''],['Input type',INPUT_TYPES[settings.inputType]||INPUT_TYPES.mixed],['Data source','openFDA NDC Directory'],...METHOD_ROWS]);
 return sheets;
}
const xml=s=>String(s??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function col(i){let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s;}
const utf8=new TextEncoder(),crcTable=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(bytes){let n=0xffffffff;for(const b of bytes)n=crcTable[(n^b)&255]^(n>>>8);return (n^0xffffffff)>>>0;}
function zip(files){const locals=[],centers=[];let offset=0,centralSize=0;for(const [name,text]of files){const bytes=utf8.encode(text),fn=utf8.encode(name),crc=crc32(bytes),local=new Uint8Array(30+fn.length),l=new DataView(local.buffer);l.setUint32(0,0x04034b50,true);l.setUint16(4,20,true);l.setUint16(6,0x800,true);l.setUint32(14,crc,true);l.setUint32(18,bytes.length,true);l.setUint32(22,bytes.length,true);l.setUint16(26,fn.length,true);local.set(fn,30);locals.push(local,bytes);const central=new Uint8Array(46+fn.length),c=new DataView(central.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint32(16,crc,true);c.setUint32(20,bytes.length,true);c.setUint32(24,bytes.length,true);c.setUint16(28,fn.length,true);c.setUint32(42,offset,true);central.set(fn,46);centers.push(central);offset+=local.length+bytes.length;centralSize+=central.length;}const end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,files.length,true);e.setUint16(10,files.length,true);e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);const out=new Uint8Array(offset+centralSize+22);let pos=0;for(const part of [...locals,...centers,end]){out.set(part,pos);pos+=part.length;}return out;}
export function xlsxBytes(sheets){if(sheets.some(s=>s.rows.some(r=>r.some(v=>String(v??'').length>32767))))throw new Error('A cell exceeds the Excel text limit. Split this batch into smaller lists.');const files=[],ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships';files.push(['[Content_Types].xml',`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`]);files.push(['_rels/.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`]);files.push(['xl/workbook.xml',`<workbook xmlns="${ns}" xmlns:r="${rel}"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`]);files.push(['xl/_rels/workbook.xml.rels',`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="styles" Type="${rel}/styles" Target="styles.xml"/></Relationships>`]);files.push(['xl/styles.xml',`<styleSheet xmlns="${ns}"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF144549"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top"/></xf><xf numFmtId="49" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"><alignment vertical="top"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0"><alignment vertical="center" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`]);
for(const [i,s]of sheets.entries()){if(s.rows.length>1048576)throw new Error('Excel row limit exceeded; split the batch.');const range=`A1:${col(s.rows[0].length-1)}${s.rows.length}`;files.push([`xl/worksheets/sheet${i+1}.xml`,`<worksheet xmlns="${ns}"><dimension ref="${range}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${s.rows[0].map((h,c)=>`<col min="${c+1}" max="${c+1}" width="${s.name==='Methods and workflow'?(c===0?28:125):/URL|notes|ingredients|name|drugs|validation/i.test(h)?44:23}" customWidth="1"/>`).join('')}</cols><sheetData>${s.rows.map((row,r)=>`<row r="${r+1}"${r===0?' ht="38" customHeight="1"':''}>${row.map((v,c)=>typeof v==='number'?`<c r="${col(c)}${r+1}" s="${r===0?2:0}"><v>${v}</v></c>`:`<c r="${col(c)}${r+1}" s="${r===0?2:1}" t="inlineStr"><is><t xml:space="preserve">${xml(String(v??''))}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="${range}"/></worksheet>`]);}return zip(files);}
export function exportWorkbook(results,settings){const bytes=xlsxBytes(buildSheets(results,settings)),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download=`Drug_name_NDC_mapping_${new Date().toISOString().slice(0,10)}${results.some(r=>r.errors.length||!r.finished)?'_PARTIAL':''}.xlsx`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return bytes.length;}
